# Generated by Django 3.0.8 on 2020-07-10 06:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('commentuser', models.CharField(max_length=20)),
                ('title', models.CharField(default='', max_length=100)),
                ('comment', models.TextField(max_length=150)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('helper', models.CharField(max_length=20)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('title', models.CharField(default='我是题目', max_length=50)),
                ('type', models.CharField(default=None, max_length=10)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('content', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('petid', models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('petname', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=1000)),
                ('owner', models.CharField(max_length=20)),
                ('type', models.CharField(default='小可爱', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Wanttohelp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('wantuser', models.CharField(max_length=20)),
                ('say', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=5)),
                ('lastname', models.CharField(max_length=5)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('email', models.EmailField(default='xxx@email.com', max_length=254)),
                ('personality', models.TextField(default='这个人很懒哦，什么都没写ฅ(๑ ̀ㅅ ́๑)ฅ', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
