# Generated by Django 3.0.8 on 2020-07-05 13:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=5)),
                ('lastname', models.CharField(max_length=5)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('email', models.EmailField(default='xxx@email.com', max_length=254)),
                ('personality', models.TextField(default='这个人很懒哦，什么都没写ฅ(๑ ̀ㅅ ́๑)ฅ', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('petname', models.CharField(max_length=20)),
                ('petid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('type', models.CharField(default='小可爱', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petsemergency.MyUser')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(default=None, max_length=10)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('content', models.TextField(max_length=2000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petsemergency.MyUser')),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Help_helper', to='petsemergency.MyUser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Help_user', to='petsemergency.MyUser')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petsemergency.Message')),
                ('commentuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment_commentuser', to='petsemergency.MyUser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment_user', to='petsemergency.MyUser')),
            ],
        ),
        migrations.CreateModel(
            name='ChatRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('summary', models.TextField(max_length=2000)),
                ('curruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Char_curr', to='petsemergency.MyUser')),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Chat_other', to='petsemergency.MyUser')),
            ],
        ),
    ]
