# Generated by Django 3.0.8 on 2020-07-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsemergency', '0002_auto_20200709_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrecord',
            name='curruser',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='chatrecord',
            name='other',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentuser',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='help',
            name='helper',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='help',
            name='user',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pets',
            name='owner',
            field=models.CharField(max_length=20),
        ),
    ]
