# Generated by Django 3.0.8 on 2020-07-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsemergency', '0003_auto_20200709_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(default='我是题目', max_length=50),
        ),
    ]
